name-template: |
  ${{ if eq(github.ref, 'refs/heads/develop') }}v${{ steps.set_version.outputs.next_patch_version }}-beta.${{ github.run_number }}${{ else }}v${{ steps.set_version.outputs.next_patch_version }}${{ end }}
tag-template: |
  ${{ if eq(github.ref, 'refs/heads/develop') }}v${{ steps.set_version.outputs.next_patch_version }}-beta.${{ github.run_number }}${{ else }}v${{ steps.set_version.outputs.next_patch_version }}${{ end }}
categories:
  - title: '🚀 New Features'
    labels:
      - feature
  - title: '🐛 Bug Fixes'
    labels:
      - bug
  - title: '🧹 Chores'
    labels:
      - chore
change-template: '- $TITLE (#$NUMBER)'
template: |
  ## Changes
  $CHANGES
