/** HL7 Class **/
export { HL7_2_1 } from "./specification/2.1";
export type { HL7_2_1_MSH } from "./specification/2.1";
export { HL7_2_2 } from "./specification/2.2";
export type { HL7_2_2_MSH } from "./specification/2.2";
export { HL7_2_3 } from "./specification/2.3";
export type { HL7_2_3_MSH } from "./specification/2.3";
export { HL7_2_3_1 } from "./specification/2.3.1";
export type { HL7_2_3_1_MSH } from "./specification/2.3.1";
export { HL7_2_4 } from "./specification/2.4";
export type { HL7_2_4_MSH } from "./specification/2.4";
export { HL7_2_5 } from "./specification/2.5";
export type { HL7_2_5_MSH } from "./specification/2.5";
export { HL7_2_5_1 } from "./specification/2.5.1";
export type { HL7_2_5_1_MSH } from "./specification/2.5.1";
export { HL7_2_6 } from "./specification/2.6";
export type { HL7_2_6_MSH } from "./specification/2.6";
export { HL7_2_7 } from "./specification/2.7";
export type { HL7_2_7_MSH } from "./specification/2.7";
export { HL7_2_7_1 } from "./specification/2.7.1";
export type { HL7_2_7_1_MSH } from "./specification/2.7.1";
export { HL7_2_8 } from "./specification/2.8";
export type { HL7_2_8_MSH } from "./specification/2.8";
export { HL7_SPEC_BASE } from "./specification/specification";
export type { HL7_SPEC, MSH } from "./specification/specification";
