name: Test
on:
  workflow_dispatch:
  workflow_call:
  pull_request:
    branches:
      - main
      - develop
    types:
      - opened
      - reopened
      - ready_for_review
      - synchronize


jobs:

  Build:
    runs-on: ubuntu-latest
    services:
      redis:
        image: redis:latest
        ports:
          - 6379:6379
        options: >-
          --health-cmd="redis-cli ping"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3
    strategy:
      matrix:
        node-version: [20.x, 'lts/*', 'latest']
    steps:
      - uses: actions/checkout@v4

      - name: Test with Node ${{matrix.node-version}}
        uses: actions/setup-node@v4
        with:
          node-version: ${{matrix.node-version}}

      - name: Pre-Run
        run: |
          npm install --package-lock-only
          npm install --ignore-scripts

      - name: Run Tests and Lint
        run: |
          npm run lint
          npm run test
        env:
          REDIS_REMOTE: true
          REDIS_HOST: localhost
          REDIS_PORT: 6379

      - name: Run Build
        run: |
          npm run build

      - name: Upload build artifact
        if: matrix.node-version == 'lts/*'
        uses: actions/upload-artifact@v4
        with:
          name: cache
          path: |
            package.json
            package-lock.json
            README.md
            LICENSE
            ./lib
