name: Test
on:
  workflow_dispatch:
  workflow_call:
  pull_request:
    branches:
      - main
      - develop
    types:
      - opened
      - reopened
      - ready_for_review
      - synchronize


jobs:

  Build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x, 'lts/*', 'latest']
    steps:
      - uses: actions/checkout@v4

      - name: Test with Node ${{matrix.node-version}}
        uses: actions/setup-node@v4
        with:
          node-version: ${{matrix.node-version}}

      - name: Pre-Run
        run: |
          npm install --package-lock-only
          npm install --ignore-scripts

      - name: Run Tests and Lint
        run: |
          npm run lint
          npm run test

      - name: Run Build
        run: |
          npm run build

      - name: Upload build artifact
        if: matrix.node-version == 'lts/*'
        uses: actions/upload-artifact@v4
        with:
          name: cache
          path: |
            package.json
            package-lock.json
            README.md
            LICENSE
            ./lib
