name: Release and Publish
on:
  release:
    types:
      - published

jobs:
  Test:
    uses: ./.github/workflows/test.yaml

  Publish:
    needs: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Create Directory
        run: mkdir -p ./lib

      - name: Download the build artifact
        uses: actions/download-artifact@v4
        with:
          name: cache
          path: ./

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
          registry-url: 'https://registry.npmjs.org/'

      - name: Get Release Version
        id: get_version
        run: |
          echo "release_version=v${{ github.event.release.tag_name }}" >> $GITHUB_ENV

      - name: Update Version in Package.json
        run: |
          npm version $release_version --no-git-tag-version
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git commit -am "chore(release): update to version $release_version"
          git push origin main

      - name: Publish to npm
        run: |
          if [[ "${{ github.ref_name }}" == "develop" ]]; then
            npm publish --tag beta
          else
            npm publish
          fi
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

  Document:
    needs: Publish
    uses: ./.github/workflows/docs.yaml

