name: Release Drafter

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - develop

jobs:
  update_release_draft:
    name: Release Drafter
    runs-on: ubuntu-latest

    steps:

      - name: Update Release Draft
        if: github.ref_name == 'develop'
        uses: release-drafter/release-drafter@v6
        with:
          prerelease: ${{ github.ref_name == 'develop' }}
          commitish: ${{ github.ref_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
