name: Test
on:
  workflow_dispatch:
  workflow_call:
  pull_request:
    branches:
      - main
      - develop
    types:
      - opened
      - synchronize

jobs:
  Build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x, 'lts/*', 'latest']
    steps:
      - uses: actions/checkout@v4

      - name: Test with Node ${{matrix.node-version}}
        uses: actions/setup-node@v4
        with:
          node-version: ${{matrix.node-version}}

      - name: Pre-Run
        run: |
          npm install --package-lock-only
          npm install --ignore-scripts
          npm run build

      - name: Run Tests and Lint
        run: |
          npm run lint
          npm run test

      - name: Upload build artifact
        if: matrix.node-version == 'lts/*'
        uses: actions/upload-artifact@v4
        with:
          name: cache
          path: |
            package.json
            package-lock.json
            ./lib

  Release_Drafter:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Draft Release (Develop)
        if: github.event.pull_request.base.ref == 'develop'
        uses: release-drafter/release-drafter@v6
        with:
          prerelease: true
          commitish: develop
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Draft Release
        if: github.event.pull_request.base.ref != 'develop'
        uses: release-drafter/release-drafter@v6
        with:
          prerelease: false
          commitish: main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}